[package]
name = "content_integrity"
version = "0.0.1"
edition = "2021"
resolver = "2"

[lib]
crate-type = ["cdylib", "rlib"]
name = "content_integrity"

[dependencies]
hdi = { workspace = true }

serde = { workspace = true }
